name: parseq_viptr
_target_: strhub.models.parseq_viptr.system.PARSeq

# Data

# Augment
# patch_drop_rate: 0.0

# Architecture
dec_num_heads: 8
dec_mlp_ratio: 4
dec_depth: 1

# Training
lr: 7e-4
perm_num: 6
perm_forward: true
perm_mirrored: true
dropout: 0.1

# Decoding mode (test)
decode_ar: true
refine_iters: 2
